// Autogenerated class. Do not modify
package works.hop.entity;

import java.lang.Integer;
import java.lang.String;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import works.hop.generate.Entity;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Account implements Entity {
  private String password;

  private LocalDateTime dateCreated;

  private Integer id;

  private String username;
}
