// Autogenerated class. Do not modify
package works.hop.entity;

import java.lang.Integer;
import java.lang.String;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import works.hop.generate.Entity;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Address implements Entity {
  private String unitNum;

  private String city;

  private Integer id;

  private String state;

  private String streetName;

  private String zipCode;

  public static void main(String[] args) throws Throwable {
    Address addr = new Address("", "city", 1, "WI", "street1", "00100");
    System.out.println(addr.getProperty("state", String.class));
  }
}
