// Autogenerated class. Do not modify
package works.hop.entity;

import java.lang.String;
import java.math.BigDecimal;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import works.hop.generate.Entity;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class MusicAlbum implements Entity {
  private LocalDate releaseDate;

  private String artist;

  private BigDecimal price;

  private String genre;

  private String producer;

  private String title;
}
