// Autogenerated class. Do not modify
package works.hop.entity;

import java.lang.Integer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import works.hop.generate.Entity;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Requested implements Entity {
  private Song song;

  private Listener listener;

  private Integer id;
}
