// Autogenerated class. Do not modify
package works.hop.entity;

import java.lang.Integer;
import java.lang.String;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import works.hop.generate.Entity;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SaleItem implements Entity {
  private Address itemLocation;

  private LocalDateTime dateAdded;

  private Integer quantity;

  private BigDecimal price;

  private Seller itemSeller;

  private String description;

  private Integer id;

  private String title;
}
