// Autogenerated class. Do not modify
package works.hop.entity;

import java.lang.Integer;
import java.lang.String;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import works.hop.generate.Entity;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Seller implements Entity {
  private String emailAddress;

  private LocalDateTime dateCreated;

  private String lastName;

  private Address billingAddress;

  private Integer id;

  private Account sellerAccount;

  private String firstName;

  private Address sellerAddress;
}
